import mongoose, { Schema, type Model, type Types } from 'mongoose';
import {
  LEAD_QUALITIES,
  LEAD_STATUSES,
  type LeadQuality,
  type LeadStatus,
} from '../constants';

export const ACTIVITY_TYPES = [
  'created',
  'note',
  'status',
  'quality',
  'assign',
  'email',
] as const;
export type ActivityType = (typeof ACTIVITY_TYPES)[number];

export interface ILeadActivity {
  _id: Types.ObjectId;
  type: ActivityType;
  message: string;
  /** Null for events generated by the public ingestion endpoint. */
  actor?: Types.ObjectId | null;
  createdAt: Date;
}

export interface ILead {
  _id: Types.ObjectId;
  site: Types.ObjectId;
  name: string;
  email?: string;
  phone?: string;
  company?: string;
  message?: string;
  status: LeadStatus;
  quality: LeadQuality;
  assignedTo?: Types.ObjectId | null;
  assignedAt?: Date | null;
  lastContactedAt?: Date | null;
  value: number;
  tags: string[];
  /** Anything extra the source form posted, kept verbatim. */
  customFields: Record<string, unknown>;
  meta: {
    source?: string;
    page?: string;
    referrer?: string;
    ip?: string;
    userAgent?: string;
    utmSource?: string;
    utmMedium?: string;
    utmCampaign?: string;
    utmTerm?: string;
    utmContent?: string;
  };
  activities: ILeadActivity[];
  createdAt: Date;
  updatedAt: Date;
}

const activitySchema = new Schema<ILeadActivity>(
  {
    type: { type: String, enum: ACTIVITY_TYPES, required: true },
    message: { type: String, required: true, maxlength: 4000 },
    actor: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    createdAt: { type: Date, default: Date.now },
  },
  { _id: true },
);

const leadSchema = new Schema<ILead>(
  {
    site: { type: Schema.Types.ObjectId, ref: 'Site', required: true },
    name: { type: String, required: true, trim: true, maxlength: 200 },
    email: { type: String, trim: true, lowercase: true, default: '' },
    phone: { type: String, trim: true, default: '' },
    company: { type: String, trim: true, default: '' },
    message: { type: String, default: '', maxlength: 5000 },
    status: {
      type: String,
      enum: LEAD_STATUSES,
      default: 'new',
      required: true,
    },
    quality: {
      type: String,
      enum: LEAD_QUALITIES,
      default: 'unrated',
      required: true,
    },
    assignedTo: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    assignedAt: { type: Date, default: null },
    lastContactedAt: { type: Date, default: null },
    value: { type: Number, default: 0, min: 0 },
    tags: { type: [String], default: [] },
    customFields: { type: Schema.Types.Mixed, default: {} },
    meta: {
      source: { type: String, default: 'website' },
      page: { type: String, default: '' },
      referrer: { type: String, default: '' },
      ip: { type: String, default: '' },
      userAgent: { type: String, default: '' },
      utmSource: { type: String, default: '' },
      utmMedium: { type: String, default: '' },
      utmCampaign: { type: String, default: '' },
      utmTerm: { type: String, default: '' },
      utmContent: { type: String, default: '' },
    },
    activities: { type: [activitySchema], default: [] },
  },
  { timestamps: true },
);

leadSchema.index({ createdAt: -1 });
leadSchema.index({ assignedTo: 1, createdAt: -1 });
leadSchema.index({ site: 1, createdAt: -1 });
leadSchema.index({ status: 1, createdAt: -1 });
leadSchema.index({ quality: 1, createdAt: -1 });

// Next.js hot-reload keeps the first compiled model; drop it so enum updates
// (e.g. activity type `quality`) take effect without a full server restart.
if (mongoose.models.Lead) {
  mongoose.deleteModel('Lead');
}

export const Lead: Model<ILead> = mongoose.model<ILead>('Lead', leadSchema);
